ppp_reportes_index:
    path:     /
    defaults: { _controller: PPPCanBundle:Reportes:index }

ppp_reportes_mascotas_exportar:
    path:     /mascotas/exportar
    defaults: { _controller: PPPCanBundle:Reportes:mascotasExportar }

ppp_reportes_radicados_exportar:
    path:     /radicados/exportar
    defaults: { _controller: PPPCanBundle:Reportes:radicadosExportar }

ppp_reportes_radicados_estado_exportar:
    path:     /radicados/exportar/estado
    defaults: { _controller: PPPCanBundle:Reportes:radicadosPorEstadoExportar }

ppp_reportes_radicados_entre:
    path:     /query/radicados
    defaults: { _controller: PPPCanBundle:Reportes:radicadosEntre }

ppp_reportes_mascotas_entre:
    path:     /query/mascotas
    defaults: { _controller: PPPCanBundle:Reportes:mascotasEntre }
